# Generated by Django 2.1.15 on 2020-04-08 20:32

import dash.csvstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(storage=dash.csvstore.OverwriteStorage(), upload_to='CSV_FOLDER/')),
            ],
        ),
        migrations.CreateModel(
            name='Prepross',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=300)),
                ('coltype', models.CharField(max_length=300)),
                ('assvar', models.CharField(max_length=300)),
                ('missingvalues', models.CharField(max_length=300)),
                ('trainingset_size', models.IntegerField()),
                ('featscaling', models.CharField(max_length=300)),
                ('ordinal', models.CharField(max_length=300)),
            ],
        ),
    ]
